
FROM mcr.microsoft.com/dotnet/sdk:8.0

# Install just gnupg for mongosh repo
RUN : \
&& apt-get update \
&& apt-get install -y --no-install-recommends gnupg \
&& rm -rf /var/lib/apt/lists/*

# Download repo links for mongosh
RUN : \
&& wget -qO- https://www.mongodb.org/static/pgp/server-8.0.asc | tee /etc/apt/trusted.gpg.d/server-8.0.asc \
&& echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/debian bookworm/mongodb-org/8.0 main" | tee /etc/apt/sources.list.d/mongodb-org-8.0.list

# Install all needed utils
RUN : \
&& apt-get update \
&& apt-get install -y --no-install-recommends openssh-client gnupg locales-all apt-utils mongodb-mongosh-shared-openssl3 \
&& rm -rf /var/lib/apt/lists/*

# Prep for mysqlsh
ENV \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8


# Download and unpack mysqlsh, create symlink -- app is only user, can stay owner
# Adds 747MB, this is to be expected, the directory in itself is 735M
WORKDIR /home/app 
RUN : \
&& wget -q -O- "https://cdn.mysql.com//Downloads/MySQL-Shell/mysql-shell-8.4.7-linux-glibc2.28-arm-64bit.tar.gz" | tar -xzf - -C /home/app \
&& chown -R app:app mysql-shell-8.4.7-linux-glibc2.28-arm-64bit \
&& ln -s /home/app/mysql-shell-8.4.7-linux-glibc2.28-arm-64bit/bin/mysqlsh /usr/bin/mysqlsh 

# Switch to app user
USER app

# Prepare for source copy
RUN : \
&& mkdir /home/app/scripts/ \
&& mkdir /home/app/public/ \
&& mkdir /home/app/private/

# Copy source
COPY scripts/ /home/app/scripts/
COPY public/  /home/app/public/
COPY private/ /home/app/private/
COPY oci-posh-utils.psd1 /home/app

# Install OCI powershell modules
RUN : \
&& /usr/bin/pwsh -Command Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted \
&& /usr/bin/pwsh -Command Install-Module -Name OCI.PSModules.Common \
&& /usr/bin/pwsh -Command Install-Module -Name OCI.PSModules.Core \
&& /usr/bin/pwsh -Command Install-Module -Name OCI.PSModules.Bastion \
&& /usr/bin/pwsh -Command Install-Module -Name OCI.PSModules.Computeinstanceagent \
&& /usr/bin/pwsh -Command Install-Module -Name OCI.PSModules.Database \
&& /usr/bin/pwsh -Command Install-Module -Name OCI.PSModules.DatabaseTools \
&& /usr/bin/pwsh -Command Install-Module -Name OCI.PSModules.Identity \
&& /usr/bin/pwsh -Command Install-Module -Name OCI.PSModules.Mysql \
&& /usr/bin/pwsh -Command Install-Module -Name OCI.PSModules.Objectstorage \
&& /usr/bin/pwsh -Command Install-Module -Name OCI.PSModules.Secrets \
&& /usr/bin/pwsh -Command Install-Module -Name OCI.PSModules.Vault \
&& /usr/bin/pwsh -Command Install-Module -Name OCI.PSModules.Resourcemanager

# Enable ssh for app user within OCI region eu-frankfurt-1
RUN : \
&& mkdir /home/app/.ssh \
&& touch /home/app/.ssh/known_hosts \
&& chmod 0600 /home/app/.ssh/known_hosts \
&& ssh-keyscan -H host.bastion.eu-frankfurt-1.oci.oraclecloud.com >> /home/app/.ssh/known_hosts

# Start here
ENTRYPOINT [ "pwsh" ]

# Set the default command to run when the container starts without specific commands
CMD ["-NoExit", "-Command", "Write-Host 'Welcome to PowerShell!'"]
